### ISSUE TITLE
release 4.0 breaks use in node?

### ISSUE THREAD

**Issue by anneb** [w8r/wms-capabilities#13]
According to documentation in README.md, wms-capabilities can now be used  with Node as follows:

`$npm install --save xmldom`
then:
```
import { DOMParser } from 'xmldom';
import WMSCapabilities from 'wms-capabilities';
...
new WMSCapabilities(xmlString, DOMParser).toJSON();
```

If the above code is used in file index.js, using node version 11.6.0
`node index.js
`
this results in error message:
Unexpected token {

After renaming index.js to index.mjs and using node experimental-modules mode, command:
`node --experimental-modules --inspect index.mjs`
results in error message:
import { DOMParser } from 'xmldom';
         ^^^^^^^^^
SyntaxError: The requested module 'xmldom' does not provide an export named 'DOMParser'

**Comment by w8r** [comment]
Hi Anne. It's `xmldom` package problem. You can fix it by either using standard require:
```js
const WMSCapabilities = require('wms-capabilities');
const DOMParser = require('xmldom').DOMParser;

const xml = '...';

console.log(new WMSCapabilities(xml, DOMParser).toJSON());
```

Or, you can access the DOMParser as a static field:
```js
import WMSCapabilities from 'wms-capabilities';
import XMLDOM from 'xmldom';

const { DOMParser } = XMLDOM;

const xml = '...';
console.log(new WMSCapabilities(xml, DOMParser).toJSON());
```

I will update the docs

**Comment by anneb** [comment]
thanks!
