### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gorshkov-leonid** [w8r/wms-capabilities#5]
Could you please specify License?

**Comment by w8r** [comment]
https://github.com/w8r/wms-capabilities/blob/master/LICENSE.md

**Comment by w8r** [comment]
:+1:

**Comment by gorshkov-leonid** [comment]
Thank you

**Comment by gorshkov-leonid** [comment]
We want to use this library as is, but I see usage of OpenLayers license on github and MIT license on [npm](https://www.npmjs.com/package/wms-capabilities). It is mistake? Is used OpenLayers license?  Could you publish zip on github, in this case license and distribute will be in one place and it will be easier to give permission to use (our license department require public http links for distributive and license and will be better have it in one place).

**Comment by w8r** [comment]
npm MIT is a mistake. I will update it.

**Comment by gorshkov-leonid** [comment]
Thank you very match
