### ISSUE TITLE
Support WMS 1.1.1

### ISSUE THREAD

**Issue by gorshkov-leonid** [w8r/wms-capabilities#6]
Now as I understand WMS 1.1.1 unsupported
Could you support WMS 1.1.1 specific: LatLonBoundingBox (instead EX_GeographicBoundingBox), SRS(instead CRS), ScaleHint(instead MinScaleDenominator/MaxScaleDenominator)...?

**Comment by gorshkov-leonid** [comment]
Input xml:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WMT_MS_Capabilities SYSTEM "http://arcims.xxx.com/wms/1.1.1/WMS_MS_Capabilities.dtd">
<WMT_MS_Capabilities version="1.1.1">
	<Service>
		<Name>OGC:WMS</Name>
		<Title>Web Map Service Netherland_new</Title>
		<Abstract>ArcIMS 9.2.0 Netherland_new Web Map Service</Abstract>
		<KeywordList>
			<Keyword>ArcIMS</Keyword>
		</KeywordList>
		<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?" xlink:type="simple"/>
		<ContactInformation>
			<ContactPersonPrimary>
				<ContactPerson/>
				<ContactOrganization/>
			</ContactPersonPrimary>
			<ContactPosition/>
			<ContactAddress>
				<AddressType>postal</AddressType>
				<Address/>
				<City/>
				<StateOrProvince/>
				<PostCode/>
				<Country/>
			</ContactAddress>
			<ContactVoiceTelephone/>
			<ContactFacsimileTelephone/>
			<ContactElectronicMailAddress/>
		</ContactInformation>
		<Fees>none</Fees>
		<AccessConstraints>none</AccessConstraints>
	</Service>
	<Capability>
		<Request>
			<GetCapabilities>
				<Format>application/vnd.ogc.wms_xml</Format>
				<DCPType>
					<HTTP>
						<Get>
							<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?" xlink:type="simple"/>
						</Get>
					</HTTP>
				</DCPType>
			</GetCapabilities>
			<GetMap>
				<Format>image/png</Format>
				<Format>image/jpeg</Format>
				<Format>image/gif</Format>
				<DCPType>
					<HTTP>
						<Get>
							<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?" xlink:type="simple"/>
						</Get>
					</HTTP>
				</DCPType>
			</GetMap>
			<GetFeatureInfo>
				<Format>application/vnd.ogc.wms_xml</Format>
				<Format>text/xml</Format>
				<Format>text/html</Format>
				<Format>text/plain</Format>
				<DCPType>
					<HTTP>
						<Get>
							<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?" xlink:type="simple"/>
						</Get>
					</HTTP>
				</DCPType>
			</GetFeatureInfo>
		</Request>
		<Exception>
			<Format>application/vnd.ogc.se_xml</Format>
			<Format>application/vnd.ogc.se_inimage</Format>
			<Format>application/vnd.ogc.se_blank</Format>
		</Exception>
		<UserDefinedSymbolization SupportSLD="1" UserLayer="0" UserStyle="1" RemoteWFS="0"/>
		<Layer noSubsets="0" opaque="0" queryable="0">
			<Title>Netherland_new</Title>
			<SRS>EPSG:4326</SRS>
			<SRS>EPSG:32631</SRS>
			<SRS>EPSG:4267</SRS>
			<SRS>EPSG:4269</SRS>
			<SRS>EPSG:4236</SRS>
			<SRS>EPSG:32631</SRS>
			<SRS>EPSG:3395</SRS>
			<LatLonBoundingBox minx="4.7621102559" miny="52.3533754905" maxx="4.7967949942" maxy="52.3699746391"/>
			<BoundingBox SRS="EPSG:32631" minx="620008.817279871" miny="5801861.22882405" maxx="622327.806060362" maxy="5803651.38811376"/>
			<Layer queryable="1">
				<Name>13</Name>
				<Title>AdminBndy1</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.237932373" miny="50.6618400189" maxx="7.3971326892" maxy="53.6196277073"/>
				<ScaleHint min="0" max="448.945"/>
			</Layer>
			<Layer queryable="1">
				<Name>12</Name>
				<Title>AdminBndy3</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.237932373" miny="50.6618400189" maxx="7.3971326892" maxy="53.6196277073"/>
			</Layer>
			<Layer queryable="1">
				<Name>11</Name>
				<Title>AdminBndy4</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.237932373" miny="50.6618400189" maxx="7.3971326892" maxy="53.6196277073"/>
				<ScaleHint min="56.118125" max="37.412083333333285"/>
			</Layer>
			<Layer queryable="1">
				<Name>10</Name>
				<Title>AdminBndy40</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.237932373" miny="50.6618400189" maxx="7.3971326892" maxy="53.6196277073"/>
				<ScaleHint min="26.188458333333283" max="374.1208333333328"/>
			</Layer>
			<Layer queryable="1">
				<Name>9</Name>
				<Title>Oceans</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="0.9686138989" miny="51.2398390988" maxx="7.3944541008" maxy="55.5216939316"/>
			</Layer>
			<Layer queryable="1">
				<Name>8</Name>
				<Title>AdminBndy5</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.2461653071" miny="50.6755803081" maxx="7.3864834915" maxy="53.5452386362"/>
				<ScaleHint min="1.8706041666666713" max="26.188458333333283"/>
			</Layer>
			<Layer queryable="1">
				<Name>7</Name>
				<Title>LandUseA</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.2502438429" miny="50.6652290348" maxx="7.3873431818" maxy="53.6125098198"/>
				<ScaleHint min="0" max="37.412083333333285"/>
			</Layer>
			<Layer queryable="1">
				<Name>6</Name>
				<Title>LandUseB</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.3369694367" miny="50.6860349304" maxx="7.282538664" maxy="53.5100670687"/>
				<ScaleHint min="0" max="37.412083333333285"/>
			</Layer>
			<Layer queryable="1">
				<Name>5</Name>
				<Title>WaterPoly</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.2530003411" miny="50.6687005331" maxx="7.3777358928" maxy="53.5381103789"/>
				<ScaleHint min="0" max="56.118125"/>
			</Layer>
			<Layer queryable="1">
				<Name>4</Name>
				<Title>RailRds</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.4823416242" miny="50.6749236433" maxx="7.3663974315" maxy="53.4871279677"/>
				<ScaleHint min="0" max="56.118125"/>
			</Layer>
			<Layer queryable="1">
				<Name>3</Name>
				<Title>WaterSeg</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="3.2604006772" miny="50.7293751658" maxx="7.3699953811" maxy="53.5620830566"/>
				<ScaleHint min="0" max="56.118125"/>
			</Layer>
			<Layer queryable="1">
				<Name>2</Name>
				<Title>Streets</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="1.2625362784" miny="50.6270065274" maxx="7.5823575368" maxy="55.3069889163"/>
				<ScaleHint min="0" max="3.7412083333333284"/>
			</Layer>
			<Layer queryable="1">
				<Name>1</Name>
				<Title>SecHwys</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="1.7444181999" miny="50.638179124" maxx="7.5134793026" maxy="54.7040454717"/>
				<ScaleHint min="0" max="37.412083333333285"/>
			</Layer>
			<Layer queryable="1">
				<Name>0</Name>
				<Title>MajHwys</Title>
				<SRS>EPSG:4326</SRS>
				<LatLonBoundingBox minx="1.2625362784" miny="50.630417316" maxx="7.5821660825" maxy="55.3069889163"/>
				<ScaleHint min="0" max="56.118125"/>
			</Layer>
		</Layer>
	</Capability>
</WMT_MS_Capabilities>`

output json:
`{
	"version": "1.1.1",
	"Service": {
		"Name": "OGC:WMS",
		"Title": "Web Map Service Netherland_new",
		"Abstract": "ArcIMS 9.2.0 Netherland_new Web Map Service",
		"KeywordList": ["ArcIMS"],
		"OnlineResource": "http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?",
		"ContactInformation": {
			"ContactPersonPrimary": {
				"ContactPerson": "",
				"ContactOrganization": ""
			},
			"ContactPosition": "",
			"ContactAddress": {
				"AddressType": "postal",
				"Address": "",
				"City": "",
				"StateOrProvince": "",
				"PostCode": "",
				"Country": ""
			},
			"ContactVoiceTelephone": "",
			"ContactFacsimileTelephone": "",
			"ContactElectronicMailAddress": ""
		},
		"Fees": "none",
		"AccessConstraints": "none"
	},
	"Capability": {
		"Request": {
			"GetCapabilities": {
				"Format": ["application/vnd.ogc.wms_xml"],
				"DCPType": [{
					"HTTP": {
						"Get": {
							"OnlineResource": "http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?"
						}
					}
				}]
			},
			"GetMap": {
				"Format": ["image/png",
				"image/jpeg",
				"image/gif"],
				"DCPType": [{
					"HTTP": {
						"Get": {
							"OnlineResource": "http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?"
						}
					}
				}]
			},
			"GetFeatureInfo": {
				"Format": ["application/vnd.ogc.wms_xml",
				"text/xml",
				"text/html",
				"text/plain"],
				"DCPType": [{
					"HTTP": {
						"Get": {
							"OnlineResource": "http://arcims.xxx.com:80/wmsconnector/com.esri.wms.Esrimap/Netherland_new?"
						}
					}
				}]
			}
		},
		"Exception": ["application/vnd.ogc.se_xml",
		"application/vnd.ogc.se_inimage",
		"application/vnd.ogc.se_blank"],
		"Layer": {
			"Title": "Netherland_new",
			"BoundingBox": [{
				"crs": "EPSG:32631",
				"extent": [620008.817279871,
				5801861.22882405,
				622327.806060362,
				5803651.38811376],
				"res": [null,
				null]
			}],
			"Layer": [{
				"Name": "13",
				"Title": "AdminBndy1",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "12",
				"Title": "AdminBndy3",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "11",
				"Title": "AdminBndy4",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "10",
				"Title": "AdminBndy40",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "9",
				"Title": "Oceans",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "8",
				"Title": "AdminBndy5",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "7",
				"Title": "LandUseA",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "6",
				"Title": "LandUseB",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "5",
				"Title": "WaterPoly",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "4",
				"Title": "RailRds",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "3",
				"Title": "WaterSeg",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "2",
				"Title": "Streets",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "1",
				"Title": "SecHwys",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			},
			{
				"Name": "0",
				"Title": "MajHwys",
				"queryable": true,
				"opaque": false,
				"noSubsets": false,
				"BoundingBox": [{
					"crs": "EPSG:32631",
					"extent": [620008.817279871,
					5801861.22882405,
					622327.806060362,
					5803651.38811376],
					"res": [null,
					null]
				}]
			}]
		}
	}
}`

Layer not contains CRS information unlike example from this repository https://htmlpreview.github.io/?https://github.com/w8r/wms-capabilities/blob/master/example/index.html

**Comment by gorshkov-leonid** [comment]
[GetCap.json.txt](https://github.com/w8r/wms-capabilities/files/181449/GetCap.json.txt)
[GetCap.xml.txt](https://github.com/w8r/wms-capabilities/files/181450/GetCap.xml.txt)

**Comment by gorshkov-leonid** [comment]
Sorry, it is mistake. Changes already in master branch, but has not released. Could you release changes?

**Comment by w8r** [comment]
published 0.3.2

**Comment by gorshkov-leonid** [comment]
Thank you and sorry:( I changed comment with description about ScaleHint. Could you add parser for scale hind also?

**Comment by w8r** [comment]
Is Min/MaxScaleDenominator gone?

**Comment by gorshkov-leonid** [comment]
Not quite, scale hint removed from WMS specification in version 1.3.0.
[As mentioned above, ScaleHint is used in the OGC specification for WMS 1.1.1. This is why sometimes the ScaleHint is also refered to as WMSScale. But this name is somewhat irritating, because in WMS 1.3.0 there is no ScaleHint anymore!](http://wiki.deegree.org/deegreeWiki/HowToUseScaleHintAndScaleDenominator).
For support WMS 1.1.1 is need to parse scale hint.

**Comment by w8r** [comment]
Should be working by now. I tested on your example

**Comment by w8r** [comment]
0.3.3 released to npm

**Comment by gorshkov-leonid** [comment]
could you publish zip on github?

**Comment by w8r** [comment]
re-published at npm with the updated license, made [0.3.4 release](https://github.com/w8r/wms-capabilities/releases/tag/0.3.4)

**Comment by gorshkov-leonid** [comment]
yet another question, in "WMS._readLayer" SRS is not inherited

**Comment by w8r** [comment]
Can you please provide a test case please?
