### ISSUE TITLE
Read more than one layer node

### ISSUE THREAD

**Issue by AntoniBCN** [w8r/wms-capabilities#8]
Hello,

I have detected that wms-capabilities only reads the last node "layer" child of node "capability" when there is more than one "layer" node. See capabilities example at http://geoserveis.icc.cat/icc_bseccen/wms/service?REQUEST=GetCapabilities&VERSION=1.3.0&service=wms where there are 14 "layer" child nodes of "capability" . 

It would be possible a workaround to return the content of all "layer" nodes that are children of "capability" node?

Thank you.

**Comment by anneb** [comment]
Indeed, the Capability node has only one Layer. I believe this is according to the specification. In your example, that root-layer currently has 15 sub-layers. These 15 sub-layers each have one or more sub-sub-layers. I think wms-capabilities parses this correctly, so this issue can be closed?

**Comment by AntoniBCN** [comment]
Yes, this issue can be closed because the capabilities document was changed in order to have one layer node, parent of 15 sub layers.
